const { Sequelize, DataTypes } = require('sequelize');

const sequelize = require('../sequelize');

const Records = sequelize.define('record',{
    name: {
        type:DataTypes.STRING,
        allowNull:false,
    },
    is_vaccinated: {
        type:DataTypes.BOOLEAN,
        allowNull:false
    },
    birthdate: {
        type:DataTypes.STRING,
        allowNull:false
    },
    gender:{
        type:DataTypes.STRING,
        allowNull:false
    },
    id: {
        type: DataTypes.INTEGER,
        allowNull: false,
        primaryKey: true,
        autoIncrement: true,
        _autoGenerated: true
      }

});

(async ()=>{
    await sequelize.sync({force:true});
})();




module.exports = Records;